import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import ReactQueryClientProvider from '@/providers/react-query-client.provider';
import { BetterAuthProvider } from '@/providers/better-auth.provider';
import { ThemeProvider } from '@/providers/theme.provider';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				suppressHydrationWarning
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<main>
						<ReactQueryClientProvider>
							<BetterAuthProvider>{children}</BetterAuthProvider>
						</ReactQueryClientProvider>
					</main>
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}
